config/routes.rb
FilmFan::Application.routes.draw do
  get "home/index"

  root :to => 'home#index'
  resources :actors do
    resources :comments
  end  

  resources :movies do
    resources :comments
  end

end

app/models/actor.rb
class Actor < ActiveRecord::Base
  attr_accessible :first_name, :last_name,:comments_attributes
  has_and_belongs_to_many :movies
  has_many :comments, :as => :commentable, :dependent => :destroy

  accepts_nested_attributes_for :comments,
                                reject_if:lambda { |attrs|
                                  attrs.all? { |key, value| value.blank? }
                                },
                                allow_destroy:true

  def with_blank_comment
    comments.build
    self
end

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  has_ancestry
  attr_accessible :content, :parent_id, :commentable_id, :commentable_type
  belongs_to :commentable, :polymorphic => true
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  attr_accessible :title, :duration,:comments_attributes,:actor_ids
  has_and_belongs_to_many :actors
  has_many :comments, :as => :commentable, :dependent => :destroy

  accepts_nested_attributes_for :comments,
                                reject_if:lambda { |attrs|
                                  attrs.all? { |key, value| value.blank? }
                                },
                                allow_destroy:true

  def with_blank_comment
    comments.build
    self
  end

  protected


end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  include FilmFan::Commentable
  
  def index
    @actors = Actor.all

  end

  def show
    @actor = Actor.find(params[:id])
  end

  def new
    @actor=Actor.new

  end

  def create
    @actor = Actor.new(params[:actor])

    respond_to do |format|
      if @actor.save
        format.html { redirect_to @actor, notice: 'Post was successfully created.' }
        format.json { render json: @actor, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @parent_id = params.delete(:parent_id)
    @commentable = find_commentable
    @comment = Comment.new( :parent_id => @parent_id, 
                            :commentable_id => @commentable.id,
                            :commentable_type => @commentable.class.to_s)
  end
  
  def create
    @commentable = find_commentable
    @comment = @commentable.comments.build(params[:comment])
    if @comment.save
      flash[:notice] = "Successfully created comment."
      redirect_to @commentable
    else
      flash[:error] = "Error adding comment."
    end
  end
 
  private
  def find_commentable
    params.each do |name, value|
      if name =~ /(.+)_id$/
        return $1.classify.constantize.find(value)
      end
    end
    nil
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  include FilmFan::Commentable
  
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end
  def new
    @movie=Movie.new

  end

  def create
    @movie = Movie.new(params[:movie])

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Post was successfully created.' }
        format.json { render json: @movie, status: :created, location: @movie }
      else
        format.html { render action: "new" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end


end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
  def nested_comments(comments)
    comments.map do |comment, sub_comments|
      content_tag(:div, render(comment), :class => "media")
    end.join.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/actors/index.html.haml
%p=link_to "Home", root_path
%h2 The Actors!
%ul
- @actors.each do |actor|
  %li=link_to actor.full_name, actor

app/views/actors/new.html.erb
<%= form_for(@actor.with_blank_comment) do |f| %>
    <% if @actor.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@actor.errors.count, "error") %> prohibited this page from being saved:</h2>

          <ul>
            <% @actor.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :first_name %><br />
      <%= f.text_field :first_name %>
    </div>
    <div class="field">
      <%= f.label :last_name %><br />
      <%= f.text_field :last_name %>
    </div>

    <%= f.fields_for(:comments) do |comments_form| %>
        <div class="field">
          <%=  comments_form.label 'Comment:' %>
          <%=  comments_form.text_field :content %>
          <%=  unless comments_form.object.new_record?
                 comments_form.check_box('_destroy') + comments_form.label('_destroy','Remove')
               end %>
        </div>
    <% end %>


    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/actors/show.html.haml
= link_to "Back to Actors", actors_path
%br
%h3= @actor.full_name
%h4= " Appears in (#{pluralize(@actor.movies.count, 'movie')})"

= nested_comments @comments
= render "comments/form"

app/views/comments/_comment.html.haml
%a.pull-left{:href=>"#"}
  %img.media-object{ :src => "/assets/anonuser.jpg", :style=> "width: 64px; height: 64px;" }
.media-body
  %h4.media-heading Anonymous User
  %i= comment.created_at.strftime('%b %d, %Y at %H:%M') 
  %p= simple_format comment.content
  .actions
    = link_to "Reply", new_polymorphic_path([@commentable, Comment.new], :parent_id => comment)
  = nested_comments comment.children

app/views/comments/_form.html.haml
= form_for [@commentable, @comment] do |f|
  = f.hidden_field :parent_id
  %p
    = f.label :content, "New comment"
    %br
    = f.text_area :content, :rows => 4
  %p
    = f.submit "Post Comment"

app/views/comments/new.html.haml
%h1 New Comment
= render 'form'

app/views/home/index.html.haml
%h2 Welcome to the Movies!
%hr
%p=link_to "All Movies", movies_path
%p=link_to "All Actors", actors_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Film Fan App
    = stylesheet_link_tag    "application", :media => "all" 
    = javascript_include_tag "application" 
    = csrf_meta_tags 
  %body
    .container
      .row
        .span4.offset4.well
          = yield

app/views/movies/index.html.haml
%p=link_to "Home", root_path
%h2 The Movies!
%ul
- @movies.each do |movie|
  %li=link_to movie.title, movie

app/views/movies/new.html.erb
<%= form_for(@movie.with_blank_comment) do |f| %>
    <% if @movie.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this page from being saved:</h2>

          <ul>
            <% @movie.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :duration %><br />
      <%= f.text_field :duration %>
    </div>

    <% Actor.all.each do |actor| %>
        <div class="checkboxform">
          <%= check_box_tag "movie[actor_ids][]", actor.id,@movie.actors.include?(actor) %>
          <label><%= actor.first_name %></label>
        </div>
    <% end %>



    <%= f.fields_for(:comments) do |comments_form| %>
        <div class="field">
          <%=  comments_form.label 'Comment:' %>
          <%=  comments_form.text_field :content %>
          <%=  unless comments_form.object.new_record?
                 comments_form.check_box('_destroy') + comments_form.label('_destroy','Remove')
               end %>
        </div>
    <% end %>


    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/movies/show.html.haml
= link_to "Back to Movies", movies_path
%br
%h3= @movie.title
%h4= " (#{@movie.duration} minutes)"

= nested_comments @comments
= render "comments/form"